---
# vim:ft=ansible:
- name: Provision REA sinatra demo app to AWS
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/aws.yml
    - vars/aws-creds.yml

  tasks:
  - name: ecr login
    tags: image
    shell: "$(aws ecr get-login --region us-east-1 --no-include-email)"

  - name: ecr repo
    tags: image
    ecs_ecr: name=rea/demo

  - name: build docker image
    tags: image
    docker_image:
      path: ../docker
      name: "{{ ecr_image_name }}"
      push: yes

  - name: ecs task definition
    tags: ecs
    ecs_taskdefinition:
      state: present
      family: rea-demo-sinatra-taskdef
      containers:
        - name: sinatra-app
          image: "{{ ecr_image_name }}"
          portMappings:
            - containerPort: 8888
              hostPort: 8888
          memory: 300

  - name: ecs cluster
    ecs_cluster:
      name: "{{ ecs_cluster_name }}"
      state: present

  - name: ecs service
    ecs_service:
      state: present
      name: rea-demo-sinatra-service
      cluster: "{{ ecs_cluster_name }}"
      desired_count: 1
      task_definition: rea-demo-sinatra-taskdef


  - name: ec2 security group
    tags: TODO
    when: false
    ec2_group:
      name: "{{ ec2_sg_name }}"
      state: present
      rules:
        - proto: tcp
          from_port: 8888
          to_port: 8888
          cidr_ip: 0.0.0.0/0

  - name: ec2 docker host for ecs
    tags: TODO
    when: false
    ec2:
      group: "{{ ec2_sg_name }}"
      image: "{{ docker_host_ami_id }}"
