---
- name: Provision REA sinatra demo app to AWS
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/aws-creds.yml

  tasks:

  - name: ECR login
    tags: image
    shell: "$(aws ecr get-login --region us-east-1 --no-include-email)"

  - name: ECR repo
    ecs_ecr: name=rea/demo

  - name: build docker image
    tags: image
    docker_image:
      path: ../docker
      name: 356561822006.dkr.ecr.us-east-1.amazonaws.com/rea/demo:latest
      push: yes

# sec group
# ACL
# VPC
# ECS cluster
# Task
# Run task
